
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: churn_db
    restart: always
    environment:
      MYSQL_DATABASE: churn_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # We will uncomment these as we implement them
  # api:
  #   build:
  #     context: .
  #     dockerfile: docker/api.Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env

  # dashboard:
  #   build:
  #     context: .
  #     dockerfile: docker/dashboard.Dockerfile
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - api
  #   env_file:
  #     - .env

volumes:
  db_data:
